spring:
  application:
    name: cokerthon
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:cokerthon-local}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    com.cotato.cokerthon: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace